### ISSUE TITLE
Please Help me   to use Jenkins plugin 

### ISSUE THREAD

**Issue by zeyangli** [BBVA/mirrorgate-jenkins-builds-collector#2]
http://10.10.20.12:8002/mirrrorgate/api
JenkinsVersion : 2.138.1
mirrorgate-publisher-0.0.7

-------------
Stack trace
java.lang.IllegalArgumentException: host parameter is null
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:213)
	at org.apache.commons.httpclient.HttpConnection.<init>(HttpConnection.java:162)
	at org.apache.commons.httpclient.SimpleHttpConnectionManager.getConnectionWithTimeout(SimpleHttpConnectionManager.java:182)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:160)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:404)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:330)
	at com.bbva.arq.devops.ae.mirrorgate.jenkins.plugin.utils.RestCall.makeRestCallGet(RestCall.java:88)
	at com.bbva.arq.devops.ae.mirrorgate.jenkins.plugin.service.DefaultMirrorGateService.testConnection(DefaultMirrorGateService.java:57)
	at jenkins.plugins.mirrorgate.MirrorGatePublisher$DescriptorImpl.doTestConnection(MirrorGatePublisher.java:107)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:784)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at com.ceilfors.jenkins.plugins.jiratrigger.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.groovy:29)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at winstone.BoundedExecutorService.lambda$scheduleNext$0(BoundedExecutorService.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kdaimiel** [comment]
Hi! It seems that you have not changed the plugin configuration. Please, can you check the configuration of the plugin in Jenkins administration panel?

**Comment by zeyangli** [comment]
use chrome access  http://10.1.1.1:8002/mirrorgate/api
return 
-------------------------
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Nov 27 01:54:15 UTC 2018
There was an unexpected error (type=Not Found, status=404).
No message available

---------------------------
Jenkins settings:

Global MirrorGate Publisher Settings
 MirrorGate Server URL: http://10.1.1.1:8002/mirrorgate/api

other is null

**Comment by zeyangli** [comment]
Hi, I configured it according to the readme documentation. Please check my configuration for me. Thank you.

**Comment by kdaimiel** [comment]
Hi! I don't understand what you mean. This plugin needs a server to send builds' information. We use it to send that information to [MirrorGate dashboard](https://github.com/BBVA/mirrorgate) Please, can you explain how you are trying to use this plugin? Thanks!

**Comment by zeyangli** [comment]
Sorry, my English is not very good. I'm from China. We want to use this great open source tool. Could you contact us later? I'm not near the computer now. Thank you

**Comment by zeyangli** [comment]
Hi， I have deployed successfully. I changed port 8080 to 8002. I tested the access /mirrorgate/api address and a 404 error occurred.My address on the configuration of jenkins is http://10.1.1.1:8002/mirrorgate/api and no credentials have been added. But when you click on the test on the right, there will be a 404 error. I am not sure if there is a problem with my deployment or if there is a problem with the api address. Request help。


This is the docker process：
---------------------------------
[root@node1]# docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                              NAMES
c9a635a84cc2        openjdk:8-jdk-slim   "sh -c 'java -Xdebug "   24 hours ago        Up 24 hours         0.0.0.0:5005->5005/tcp, 0.0.0.0:8002->8080/tcp   tests_app_run_1_e0f20570b88d
67e5f084f708        mongo:3.4            "docker-entrypoint.sh"   24 hours ago        Up 24 hours         0.0.0.0:27017->27017/tcp                         tests_mongo_1_6028129773fe
----------------------------------
This is a test request：
----------------------------------
[root@node1 ~]# curl http://127.0.0.1:8002/mirrorgate/api -v
* About to connect() to 127.0.0.1 port 8002 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8002 (#0)
> GET /mirrorgate/api HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8002
> Accept: */*
>
< HTTP/1.1 404
< X-Application-Context: application:embedded
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 28 Nov 2018 02:04:46 GMT
<
* Connection #0 to host 127.0.0.1 left intact
{"timestamp":1543370686395,"status":404,"error":"Not Found","message":"No message available","path":"/mirrorgate/api"}
----------------------------------

**Comment by zeyangli** [comment]
My God, it turned out that I forgot to fill in the Extra urls.

**Comment by kdaimiel** [comment]
There is no need to complete Extra URLs. Please, check if MirrorGate Server is Up with:
curl http://127.0.0.1:8002/mirrorgate/health -v

Take in consideration that "mirrorgate/api" is just a relative path.

**Comment by zeyangli** [comment]
I am very sorry to bother, it is my configuration error. I tested this to be normal and returned to status Up. It is not necessary to write the mirrorgate/api without the address, and directly write the mirrorgate/.

**Comment by zeyangli** [comment]
**Stack trace  
java.lang.IllegalArgumentException: host parameter is null**

This error is because the address was not saved and the test connection button was clicked directly, so something went wrong.

**Comment by kdaimiel** [comment]
Ok! Thanks for reporting!!
